name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - edge-functions
    paths:
      - 'server/supabase/functions/reload-odai/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate Supabase CLI
      run: |
        echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | npx supabase login --token -

    - name: Set Supabase secrets
      run: |
        npx supabase secrets set PROJECT_ID="${{ secrets.PROJECT_ID }}"
        npx supabase secrets set PROJECT_URL="${{ secrets.PROJECT_URL }}"
        npx supabase secrets set ANON_KEY="${{ secrets.ANON_KEY }}"
        npx supabase secrets set ODAI_API_URL="${{ secrets.ODAI_API_URL }}"
        npx supabase secrets set SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

    - name: Deploy Edge Function to Supabase
      run: npx supabase functions deploy reload_odai --directory ./server/supabase/functions/reload_odai
