name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'server/supabase/functions/**'

jobs:
  deploy_edge_function:
    name: Deploy Edge Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate Supabase CLI
        run: npx supabase login --token ${{ secrets.ACCESS_TOKEN }}
        working-directory: server/supabase
      - name: Link Supabase Project
        run: npx supabase link --project-ref ${{ secrets.PROJECT_ID }}
        working-directory: server/supabase
      - name: Set Supabase secrets
        run: |
          npx supabase secrets set PROJECT_URL="${{ secrets.PROJECT_URL }}"
          npx supabase secrets set ANON_KEY="${{ secrets.ANON_KEY }}"
          npx supabase secrets set ODAI_API_URL="${{ secrets.ODAI_API_URL }}"
          npx supabase secrets set SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
        working-directory: server/supabase
      - name: Deploy Edge Function to Supabase
        run: npx supabase functions deploy reload-odai
        working-directory: server/supabase/functions/reload-odai
