name: Apply Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'server/supabase/migrations/**'

jobs:
  apply_migrations:
    name: Apply Database Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate Supabase CLI
        run: npx supabase login --token ${{ secrets.ACCESS_TOKEN }}
        working-directory: server/supabase
      - name: Remove old config.toml if exists
        run: rm -f config.toml
        working-directory: server/supabase
      - name: Initialize Supabase project configuration
        run: npx supabase init --force
        working-directory: server/supabase
      - name: Link Supabase Project
        run: npx supabase link --project-ref ${{ secrets.PROJECT_ID }}
        working-directory: server/supabase
      - name: Apply Database Migrations
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: npx supabase db push --debug
        working-directory: server/supabase
