name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - edge-functions # `edge-functions` ブランチの変更をトリガー
    paths:
      - 'server/supabase/functions/reload-odai/**' # Edge Functionのコードが変更された場合のみ実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Supabase CLI を npm 経由でインストール
    - name: Install Supabase CLI
      run: |
        npm install -g supabase
        echo "$(npm root -g)/supabase" >> $GITHUB_PATH

    # 3. Supabase の環境変数を設定
    - name: Set Supabase secrets
      run: |
        supabase secrets set PROJECT_ID="${{ secrets.PROJECT_ID }}"
        supabase secrets set PROJECT_URL="${{ secrets.PROJECT_URL }}"
        supabase secrets set ANON_KEY="${{ secrets.ANON_KEY }}"
        supabase secrets set ODAI_API_URL="${{ secrets.ODAI_API_URL }}"
        supabase secrets set SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

    # 4. Edge Functions をデプロイ
    - name: Deploy Edge Function to Supabase
      run: supabase functions deploy reload_odai --directory ./server/supabase/functions/reload_odai --watch
