name: Deploy Supabase Changes

on:
  push:
    branches:
      - 'edge-functions'  # Edge Functions & Database Functions のブランチ
    paths:
      - 'server/supabase/functions/reload-odai/**'  # Edge Functions
      - 'server/supabase/migrations/**'  # Database Migrations

jobs:
  # データベースマイグレーションの適用
  apply_migrations:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'server/supabase/migrations/')  # マイグレーションの変更時に実行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate Supabase CLI
      run: |
        echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | npx supabase login --token -

    - name: Apply Database Migrations
      run: npx supabase db push

  # Edge Functions のデプロイ
  deploy_edge_function:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'server/supabase/functions/reload-odai/')  # Edge Functions の変更時に実行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate Supabase CLI
      run: |
        echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | npx supabase login --token -

    - name: Set Supabase secrets
      run: |
        npx supabase secrets set PROJECT_ID="${{ secrets.PROJECT_ID }}"
        npx supabase secrets set PROJECT_URL="${{ secrets.PROJECT_URL }}"
        npx supabase secrets set ANON_KEY="${{ secrets.ANON_KEY }}"
        npx supabase secrets set ODAI_API_URL="${{ secrets.ODAI_API_URL }}"
        npx supabase secrets set SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

    - name: Deploy Edge Function to Supabase
      run: npx supabase functions deploy reload_odai --directory ./server/supabase/functions/reload-odai
